apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: map-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-db
  labels:
    app: map-db
    service: map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-db
      service: map
  template:
    metadata:
      labels:
        app: map-db
        service: map
    spec:
      serviceAccountName: map-db
      
      containers:
      - name: map-db-container
        image: mysql
        ports:
        - containerPort: 3306
        
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"