apiVersion: v1
kind: Service
metadata:
  name: map-db
  labels:
    app: map-db
    service: map
spec:
  selector:
    app: map-db
    service: map
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP