apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: map

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: map
  labels:
    app: map
    service: map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
      service: map
  template:
    metadata:
      labels:
        app: map
        service: map
    spec:
      serviceAccountName: map
      
      containers:
      - name: map-container
        image: hhana982/map:1.<version>
        ports:
        - containerPort: 5000
        
        env: 