apiVersion: v1
kind: Service
metadata:
  name: map
  labels:
    app: map
    service: map
spec:
  selector:
    app: map
    service: map
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP